data_ingestion:
  period: "1y"      
  interval: "1d"     

model_training:
  epochs: 20
  batch_size: 32
  lstm_units_1: 64
  lstm_units_2: 64
  dense_units_1: 128
  dropout_rate: 0.5

data_transformation:
  lookback: 60
  feature: Close