data_ingestion:
  period: "15d"       # last 15 days
  interval: "1h"     # hourly data

model_training:
  epochs: 20
  batch_size: 32
  lstm_units_1: 64
  lstm_units_2: 64
  dense_units_1: 128
  dropout_rate: 0.5